import { GiftBox, PackagingOption } from './types';

export const GIFT_BOXES_2026: GiftBox[] = [
  {
    id: 'gift-box-01',
    slug: 'gift-box-01',
    code: '01',
    title: 'Premium Dry Fruit Combo',
    subtitle: '5 Jar Gift Box',
    jarsCount: 5,
    jarWeight: '175–200 g each',
    price: 1530,
    image: '/images/gifting/gift-box-01.jpg',
    badge: 'Popular Choice',
    presentation: [
      'Premium gold-embossed presentation box',
      'Curated glass jar assortment',
      'Protective cushioned partitions',
      'Suitable for festive & corporate gifting',
    ],
    curatedItems: [
      'Almond Honey Rose (175–200g)',
      'Cashew Cheese & Herbs (175–200g)',
      'Mix Trail (175–200g)',
      'Sahi Paan Raisin (175–200g)',
      'Plain California Almond (175–200g)',
    ],
    giftingNote: [
      'Elegant presentation designed to impress',
      'Curated harmony of savoury, sweet & wholesome',
      'Premium tactile finish with gold accents',
    ],
    idealFor: ['Festive Family Gifting', 'Corporate Client Gifts', 'Diwali Celebrations'],
  },
  {
    id: 'gift-box-02',
    slug: 'gift-box-02',
    code: '02',
    title: 'Premium Dry Fruit & Treats Combo',
    subtitle: '5 Jar Gift Box',
    jarsCount: 5,
    jarWeight: '175–200 g each',
    price: 1675,
    image: '/images/gifting/gift-box-02.jpg',
    badge: '5 Exquisite Flavours',
    presentation: [
      'Rigid luxury slip-cover gift box',
      'Curated 5-jar artisanal assortment',
      'Satin ribbon detailing and branding seal',
      'Designed for executive & celebration gifting',
    ],
    curatedItems: [
      '12 in 1 Vitality Mix (175–200g)',
      'Raisin Sahi Paan (175–200g)',
      'Hazelnut Malai Rose (175–200g)',
      'Cashew Cheese & Herb (175–200g)',
      'Almond Dark Chocolate (175–200g)',
    ],
    giftingNote: [
      'A healthy indulgence meeting decadent treats',
      'Flavours curated to suit multi-generational taste',
      'Handcrafted packaging with luxury tactile feel',
    ],
    idealFor: ['Executive Corporate Hampers', 'Wedding Welcomes', 'Milestone Celebrations'],
  },
  {
    id: 'gift-box-03',
    slug: 'gift-box-03',
    code: '03',
    title: 'Premium Nuts & Treats',
    subtitle: '6 Jar Gift Box',
    jarsCount: 6,
    jarWeight: '175–200 g each',
    price: 1850,
    image: '/images/gifting/gift-box-03.jpg',
    badge: '6 Exquisite Flavours',
    presentation: [
      'Spacious double-row 6-jar luxury box',
      'Gold foil emblem with HariPrasadam signature',
      'Padded lid with elegant interior ribbon',
      'Perfect balance of tradition & wellness',
    ],
    curatedItems: [
      '12 in 1 Mix (175–200g)',
      'Raisin Sahi Paan (175–200g)',
      'Almond Malai Rose (175–200g)',
      'Cashew Dark Chocolate (175–200g)',
      'Dates Assorted (175–200g)',
      'Almond Thandai Kesar (175–200g)',
    ],
    giftingNote: [
      'Six unique flavours in one memorable box',
      'Share goodness. Share happiness.',
      'Signature presentation designed to be remembered',
    ],
    idealFor: ['High-Value Corporate Clients', 'Diwali Grand Hampers', 'Wedding Trousseau'],
  },
  {
    id: 'gift-box-04',
    slug: 'gift-box-04',
    code: '04',
    title: 'Premium Nuts & Treats',
    subtitle: '6 Jar Gift Box',
    jarsCount: 6,
    jarWeight: '175–200 g each',
    price: 1875,
    image: '/images/gifting/gift-box-04.jpg',
    badge: 'Six Special Flavours',
    presentation: [
      'Customized compartmentalized gift trunk',
      'Gold foil embossed branding',
      'Airtight glass jars with golden metal lids',
      'Suitable for elite corporate and personal gifting',
    ],
    curatedItems: [
      'Cashew Cheese & Herbs (175–200g)',
      'Dates Kunafa (175–200g)',
      'Almond Honey Rose (175–200g)',
      'Raisin Sahi Paan (175–200g)',
      'Hazelnut Malai Rose (175–200g)',
      '12 in 1 Vitality Mix (175–200g)',
    ],
    giftingNote: [
      'Six special flavours, one memorable box',
      'Goodness in every bite',
      'Refined finish crafted for discerning recipients',
    ],
    idealFor: ['Boardroom Gifting', 'VIP Wedding Guests', 'Annual Festive Appreciation'],
  },
  {
    id: 'gift-box-05',
    slug: 'gift-box-05',
    code: '05',
    title: 'Premium Nuts & Treats',
    subtitle: '6 Jar Gift Box',
    jarsCount: 6,
    jarWeight: '175–200 g each',
    price: 1975,
    image: '/images/gifting/gift-box-05.jpg',
    badge: 'The Grand Collection',
    presentation: [
      'Flagship 6-jar presentation box',
      'Opulent textured outer casing with gold inlay',
      'Individual jar pedestals with velvet cushioning',
      'The pinnacle of HariPrasadam gifting art',
    ],
    curatedItems: [
      'Dates Kunafa / Assorted (175–200g)',
      'Raisin Sahi Paan (175–200g)',
      'Cashew Cheese & Herb (175–200g)',
      'Hazelnut Malai Rose (175–200g)',
      'Almond Dark Chocolate (175–200g)',
      '12 in 1 Mix Trail (175–200g)',
    ],
    giftingNote: [
      'Nutrition, taste, tradition together',
      'Our most comprehensive and luxurious assortment',
      'Leaves an indelible impression of prestige',
    ],
    idealFor: ['Top-tier Leadership Gifts', 'Royal Celebrations', 'Luxury Hampers'],
  },
];

// Catalogue Box & Jute Packaging Options from Dry Fruit Catalog
export const CATALOGUE_PACKAGING: PackagingOption[] = [
  {
    id: 'peacock-box',
    title: 'Combo 1: Premium Peacock Gift Box',
    type: 'gift-box',
    price: 725,
    image: '/images/packaging/peacock-gift-box.jpg',
    weight: '100–125 g each (4 jars / compartments)',
    items: ['Sahi Paan Raisin', 'Cashew Cheese & Herbs', 'Almond Honey Rose', 'Mix Trail'],
    tag: 'Artisan Floral Box',
  },
  {
    id: 'floral-box',
    title: 'Combo 2: Premium Floral Gift Box',
    type: 'gift-box',
    price: 780,
    image: '/images/packaging/floral-gift-box.jpg',
    weight: '100–125 g each (4 jars / compartments)',
    items: ['Cashew Lemon Chilli', 'Hazelnut Malai Rose', 'Almond Dark', '9 in 1 Breakfast Mix'],
    tag: 'Floral Artwork Finish',
  },
  {
    id: 'compartment-box',
    title: 'Combo 3: Premium Compartment Gift Box',
    type: 'gift-box',
    price: 900,
    image: '/images/packaging/compartment-gift-box.jpg',
    weight: '100–125 g each (5 compartments)',
    items: ['Plain Almond', 'Plain Cashew', 'Kunafa Dates', '12 in 1 Mix', 'Sahi Paan Raisin'],
    tag: '5-Compartment Classic',
  },
  {
    id: 'snack-box',
    title: 'Combo 4: Premium Snack Box',
    type: 'gift-box',
    price: 980,
    image: '/images/packaging/snack-gift-box.jpg',
    weight: '100–125 g each (5 flavours)',
    items: ['Lotus Biscoff Cashew', 'Dryfruit Muesli', 'Dates Mix', 'Almond Thandai Kesar', 'Statue Pistachio'],
    tag: 'Gourmet Snack Suite',
  },
  {
    id: 'artisan-vase-box',
    title: 'Combo 5: Artisan Vase Print Gift Box',
    type: 'gift-box',
    price: 1125,
    image: '/images/packaging/artisan-vase-gift-box.jpg',
    weight: '100 g each (6 varieties)',
    items: ['Cheese Herb Cashew', 'Hazelnut Malai Rose', 'Almond Jamun', 'Sahi Paan Raisin', 'Dates Kunafa', '12 in 1 Mix'],
    tag: '6 Varieties Artisan Box',
  },
  {
    id: 'paisley-box',
    title: 'Combo 6: Ribbon-Tied Paisley Gift Box',
    type: 'gift-box',
    price: 1175,
    image: '/images/packaging/paisley-gift-box.jpg',
    weight: '100 g each (6 varieties)',
    items: ['Pistachio', 'Almond Thandai Kesar', 'Cashew Lemon Chilli', 'Dates Dark Choco', 'Mix Trail', 'Dark Chocolate Raisin'],
    tag: 'Ribbon Paisley Finish',
  },
  {
    id: 'branded-jute-1',
    title: 'Combo 1: Branded Jute Bag (With Logo)',
    type: 'branded-jute',
    price: 900,
    image: '/images/packaging/branded-jute-bag-1.jpg',
    weight: '100–125 g each (4 varieties)',
    items: ['Sahi Paan Raisin', 'Cashew Cheese & Herbs', 'Almond Honey Rose', 'Mix Trail'],
    tag: 'Eco-Luxury Jute with Logo',
  },
  {
    id: 'branded-jute-2',
    title: 'Combo 2: Branded Jute Bag (With Logo)',
    type: 'branded-jute',
    price: 950,
    image: '/images/packaging/branded-jute-bag-2.jpg',
    weight: '100–125 g each (4 varieties)',
    items: ['Cashew Lemon Chilli', 'Hazelnut Malai Rose', 'Almond Dark', '9 in 1 Breakfast'],
    tag: 'Eco-Luxury Jute with Logo',
  },
  {
    id: 'branded-jute-3',
    title: 'Combo 3: Branded Jute Bag (With Logo)',
    type: 'branded-jute',
    price: 1080,
    image: '/images/packaging/branded-jute-bag-3.jpg',
    weight: '100–125 g each (5 varieties)',
    items: ['Plain Cashew', 'Plain Almond', 'Kunafa Dates', '12 in 1 Mix', 'Sahi Paan Raisin'],
    tag: '5 Varieties Branded Jute',
  },
  {
    id: 'branded-jute-4',
    title: 'Combo 4: Branded Jute Bag (With Logo)',
    type: 'branded-jute',
    price: 1180,
    image: '/images/packaging/branded-jute-bag-4.jpg',
    weight: '100–125 g each (5 varieties)',
    items: ['Lotus Biscoff Cashew', 'Dryfruit Muesli', 'Dates Mix', 'Almond Thandai Kesar', 'Statue Pistachio'],
    tag: '5 Varieties Branded Jute',
  },
  {
    id: 'plain-jute-1',
    title: 'Combo 1: Plain Jute Bag (Without Logo)',
    type: 'plain-jute',
    price: 830,
    image: '/images/packaging/plain-jute-bag-1.jpg',
    weight: '100–125 g each (4 varieties)',
    items: ['Sahi Paan Raisin', 'Cashew Cheese & Herbs', 'Almond Honey Rose', 'Mix Trail'],
    tag: 'Natural Jute Packaging',
  },
  {
    id: 'plain-jute-2',
    title: 'Combo 2: Plain Jute Bag (Without Logo)',
    type: 'plain-jute',
    price: 875,
    image: '/images/packaging/plain-jute-bag-2.jpg',
    weight: '100–125 g each (4 varieties)',
    items: ['Cashew Lemon Chilli', 'Hazelnut Malai Rose', 'Almond Dark', '9 in 1 Breakfast'],
    tag: 'Natural Jute Packaging',
  },
  {
    id: 'plain-jute-3',
    title: 'Combo 3: Plain Jute Bag (Without Logo)',
    type: 'plain-jute',
    price: 980,
    image: '/images/packaging/plain-jute-bag-3.jpg',
    weight: '100–125 g each (5 varieties)',
    items: ['Plain Cashew', 'Plain Almond', 'Kunafa Dates', '12 in 1 Mix', 'Sahi Paan Raisin'],
    tag: 'Natural Jute Packaging',
  },
  {
    id: 'plain-jute-4',
    title: 'Combo 4: Plain Jute Bag (Without Logo)',
    type: 'plain-jute',
    price: 1125,
    image: '/images/packaging/plain-jute-bag-4.jpg',
    weight: '100–125 g each (5 varieties)',
    items: ['Lotus Biscoff Cashew', 'Dryfruit Muesli', 'Dates Mix', 'Almond Thandai Kesar', 'Statue Pistachio'],
    tag: 'Natural Jute Packaging',
  },
  {
    id: '4-mix-400',
    title: '4 Mix Gift Box (Standard Edition)',
    type: 'pocket-mix',
    price: 400,
    image: '/images/gifting/4-mix-gift-box-400.jpg',
    weight: '80–85 gm each (4 varieties)',
    items: ['Almond Plain/Honey Rose', '9 in 1 Breakfast', 'Honey Rose', 'Sahi Paan Raisin'],
    tag: 'Affordable Festive Favour',
  },
  {
    id: '4-mix-450',
    title: '4 Mix Gift Box (Deluxe Edition)',
    type: 'pocket-mix',
    price: 450,
    image: '/images/gifting/4-mix-gift-box-450.jpg',
    weight: '80–85 gm each (4 varieties)',
    items: ['Almond Premium', '9 in 1 Breakfast', 'Honey Rose Cashew', 'Sahi Paan Raisin'],
    tag: 'Affordable Festive Favour',
  },
];
